feat: add API mode
sufst/on-car-telemetry pull request #33
Opened 2023-03-22 16:10 UTC by rureverek

### Changes
- Add STM32 + ThreadX Port for [Digi XBee ANSI C Library](https://github.com/sufst/xbee_ansic_library)
- Add Xbee_comms thread responsible for sending API Explicit Transmit Request Command to attached Xbee using ported Lib

### Related Issue(s)
Closes #32 

### Additional Notes
Tested and proved to work in Autolab

2023-03-22 16:14 UTC, rureverek commented
Paths for reference: 
Xbee Lib: `src\Middlewares\SUFST\xbee-stm32`
STM32 Port: `src\Middlewares\SUFST\xbee-stm32\src\stm32`

2023-03-23 12:34 UTC, t-bre commented
@rureverek is the XBee port from [`sufst/xbee_ansic_library`](https://github.com/sufst/xbee_ansic_library)? If so, could you make it a submodule before I review this, it's a lot of files otherwise.

2023-03-23 13:01 UTC, rureverek commented
> @rureverek is the XBee port from [`sufst/xbee_ansic_library`](https://github.com/sufst/xbee_ansic_library)? If so, could you make it a submodule before I review this, it's a lot of files otherwise.

@t-bre 
Yes, but  [`sufst/xbee_ansic_library`](https://github.com/sufst/xbee_ansic_library) also contains irrelevant stuff like other ports, samples etc.  Also the user would need to run ./build.sh to create lib specifically for STM32. Are you sure you want to import the whole library?

Alternatively, I could import whole submodule, use build script and tell github to not ignore `build` dir. Then, this would work similarly like in can-defs. Should I do something like this?

2023-03-23 13:03 UTC, t-bre commented
It's fine if it contains other ports and samples, it's just files that exist within the submodule they aren't version controlled by this repo. It shouldn't affect the build system right? Unless you mean it has to be built separately, in which case we might need to add some new Makefile recipe.

2023-03-23 13:11 UTC, rureverek commented
Yes, currently its built separately, but I believe it doesn't have to be. The current build system is based on other porting (mbed), and its only simple script which changes some include file's names to be compatible with it. 
Again, now I think we don't need that script at all, so I'll try to create submodule and simplify that.

2023-03-23 14:14 UTC, rureverek commented
@t-bre All good now.

2023-03-23 18:17 UTC, t-bre requested changes
Looks good, we should test this fully before merging and a couple small tweaks to make.

2023-03-23 18:17 UTC, t-bre commented on src/SUFST/src/xbee_comms.c
> +xbee_serial_t xbee_serial;
Should `xbee_serial_t` and `xbee_dev_t` be part of the context for this module?

2023-03-23 18:17 UTC, t-bre commented on src/SUFST/src/xbee_comms.c
> +const xbee_dispatch_table_entry_t xbee_frame_handlers[] = {
Should be `static`

2023-03-23 18:17 UTC, t-bre commented on src/SUFST/src/xbee_comms.c
> +const wpan_endpoint_table_entry_t sample_endpoints[] = {
Should be `static`?

2023-03-23 18:17 UTC, t-bre commented on src/SUFST/src/xbee_comms.c
> +
Check `tx_status` before init XBee?

2023-03-23 18:17 UTC, t-bre commented on src/SUFST/src/xbee_comms.c
> +#define QUEUE_SEND_THREAD_PRIORITY             10
Constants named correctly? I think this should have prefix `XBEE_COMMS_` rather than `QUEUE_SEND_`.

2023-03-23 18:17 UTC, t-bre commented on src/SUFST/src/xbee_comms.c
> +                               TX_AUTO_START);
Maybe only start thread if XBee init happens successfully?

2023-03-23 18:17 UTC, t-bre commented on src/SUFST/src/xbee_comms.c
> +    return;
Function should return `int`?

2023-03-23 18:17 UTC, t-bre commented on src/SUFST/src/xbee_comms.c
> +    pdu_t* rx;
Maybe call this `rd_pdu_ptr` or something? Just to be more clear.

2023-04-04 15:54 UTC, rureverek commented
@t-bre Shall we push it now? It wasn't tested with CAN hardware, but the CAN handling was proved before so we can assume it works?

2023-04-06 13:52 UTC, t-bre approved these changes
Looks good, might be some small tweaks to make with further testing but I think we can merge this now.

2023-04-06 14:33 UTC, merged